const LEVEL1 = [
    "OPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWJI",
    "DALBBWBBBBBBBBBBBBBBKWBBBBBWBBBBBBBBBBBBBBBKWBBEUV",
    "DRLBBWBWWWBWWWBWWWWWWWBWWWBWBWWBWWWWWWWWWBWWWBBECV",
    "DALBBBBWBBBWBWBWBBBBBBBWBWBBBWBBBBBBBBWBWBBWBBBEUV",
    "DRLBBBBWBWWWBWBWBBWBWWWWBBBWBBBBBBWBBBWBWWBWBBBECV",
    "DALBBWWWBWWBBWBWWWWBWBBWBWBWBWBBWWWWBBWBBWBBWBBEUV",
    "OPSBBWBBBBBBWWBBBBWBBBBWBWBWBWBBBBBWBBWBBWWBWBBEJI",
    "DALBBWBWWWWWWBBWWBWBWBBBBBBWBWBBBBBWBBWBBBBBWBBEUV",
    "DRLBBBBWBBWBBBWWBBBBWWWWBWBWBWWWWWWWBBWBWWWBBBBECV",
    "DALBBBBWBBBBBBBBBMWBBWBBBWBBBWMBBBBBBBWBBBWBBBBEUV",
    "DRLBBWWWWWWWBWWWWWWWBWWWWWBWWWWWWWWWWBWWWWWBWBBECV",
    "DALBBWBBBBBBBBBBBBBBBBBBBBMWKBBBBBBBBBBBBBBBWBBEUV",
    "OPWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWJI"
]